export const queryKeys = {
  events: ["events"] as const,
  categories: ["categories"] as const,
  categoryTree: ["category-tree"] as const,
  homeCategoryChips: ["home-category-chips"] as const,
  products: (params?: { categoryID?: number; sort?: string; q?: string }) => ["products", params] as const,
  plpInformation: ["plp-information"] as const,
  plpProducts: (params?: unknown) => ["plp-products", params] as const,
  product: (id: number) => ["product", id] as const,
  productReviews: (id: number) => ["product-reviews", id] as const,
  personalizedProducts: (params?: { sort?: string }) => ["personalized-products", params] as const,
  me: (memberID: number | null | undefined) => ["me", memberID] as const,
  recommendationOnboarding: (memberID: number | null | undefined) => ["recommendation-onboarding", memberID] as const,
  homeMe: (memberID: number | null | undefined) => ["home-me", memberID] as const,
  cart: (memberID: number | null | undefined) => ["cart", memberID] as const,
  order: (orderCode: string, memberID: number | null | undefined) => ["order", memberID, orderCode] as const,
  orders: (memberID: number | null | undefined) => ["orders", memberID] as const,
  coupons: (memberID: number | null | undefined) => ["coupons", memberID] as const,
  issuableCoupons: (memberID: number | null | undefined) => ["issuable-coupons", memberID] as const,
  addresses: (memberID: number | null | undefined) => ["addresses", memberID] as const,
  wishlist: (memberID: number | null | undefined) => ["me-wishlist", memberID] as const,
  likedProducts: (memberID: number | null | undefined) => ["me-liked-products", memberID] as const,
  marketFollow: (marketID: number, memberID: number | null | undefined) => ["market-follow", marketID, memberID] as const,
  myReviews: (memberID: number | null | undefined) => ["me-reviews", memberID] as const,
  integratedSearch: (params: { q: string; audience: string; productPage: number; marketPage: number }) => ["integrated-search", params] as const,
  searchSuggestions: (q: string) => ["search-page-suggestions", q] as const,
  trendingSearches: (segment: string) => ["trending-searches", segment] as const,
};
